-- ============================================================
-- PCS Document Request System - Complete Database Schema
-- Based on ERD Diagram (Untitled_Diagram.drawio.xml)
-- ============================================================

-- 1. ENUM TYPE
CREATE TYPE public.app_role AS ENUM ('student', 'admin');

-- ============================================================
-- 2. TABLES
-- ============================================================

-- AUTH_USERS (managed by Supabase Auth - DO NOT CREATE MANUALLY)
-- Columns: user_id (UUID, PK), email (VARCHAR), created_at (TIMESTAMPTZ)

-- USER_ROLES
CREATE TABLE public.user_roles (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  role app_role NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  UNIQUE (user_id, role)
);

-- STUDENTS
CREATE TABLE public.students (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  username TEXT NOT NULL,
  first_name TEXT NOT NULL,
  middle_name TEXT,
  last_name TEXT NOT NULL,
  contact_number TEXT,
  grade_level TEXT,
  section TEXT,
  avatar_url TEXT,
  student_id TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ADMINS
CREATE TABLE public.admins (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  username TEXT NOT NULL,
  first_name TEXT NOT NULL,
  middle_name TEXT,
  last_name TEXT NOT NULL,
  contact_number TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- DOCUMENT_REQUESTS
CREATE TABLE public.document_requests (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  request_number INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  student_name TEXT NOT NULL,
  contact_number TEXT NOT NULL,
  grade_level TEXT NOT NULL,
  section TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
    -- Allowed values: pending | Processing | Approved | Ready | Completed | Cancelled
  payment_method TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- DOCUMENT_REQUEST_ITEMS
CREATE TABLE public.document_request_items (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  request_id UUID NOT NULL,
  document_type TEXT NOT NULL,
  price NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- PAYMENTS
CREATE TABLE public.payments (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  request_id UUID NOT NULL,
  user_id UUID NOT NULL,
  amount NUMERIC NOT NULL,
  payment_method TEXT NOT NULL,
  payment_status TEXT NOT NULL DEFAULT 'pending',
    -- Allowed values: pending | processing | completed | paid | failed | refunded
  reference_number TEXT,
  paid_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- FEEDBACK
CREATE TABLE public.feedback (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  email TEXT NOT NULL,
  message_type TEXT NOT NULL,
    -- Allowed values: inquiry | complaint | suggestion | feedback
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'unread',
    -- Allowed values: unread | read | resolved
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ANNOUNCEMENTS
CREATE TABLE public.announcements (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  created_by UUID,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- ============================================================
-- 3. FOREIGN KEY CONSTRAINTS
-- ============================================================

-- document_request_items.request_id → document_requests.id
ALTER TABLE public.document_request_items
  ADD CONSTRAINT document_request_items_request_id_fkey
  FOREIGN KEY (request_id) REFERENCES public.document_requests(id);

-- payments.request_id → document_requests.id (one-to-one)
ALTER TABLE public.payments
  ADD CONSTRAINT payments_request_id_fkey
  FOREIGN KEY (request_id) REFERENCES public.document_requests(id);

-- ============================================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ============================================================

-- Enable RLS on all tables
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_request_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 5. FUNCTIONS
-- ============================================================

-- Security definer function to check roles (prevents RLS recursion)
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id AND role = _role
  )
$$;

-- Format request ID as REQ-001, REQ-002, etc.
CREATE OR REPLACE FUNCTION public.get_formatted_request_id(req_number INTEGER)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
SET search_path = public
AS $$
  SELECT 'REQ-' || LPAD(req_number::text, 3, '0')
$$;

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql
SET search_path = public;

-- Handle new user registration (creates role + profile)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  user_role TEXT;
BEGIN
  user_role := COALESCE(NEW.raw_user_meta_data ->> 'role', 'student');

  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, user_role::app_role);

  IF user_role = 'admin' THEN
    INSERT INTO public.admins (user_id, username, first_name, last_name, middle_name, contact_number)
    VALUES (
      NEW.id,
      COALESCE(NEW.raw_user_meta_data ->> 'username', NEW.email),
      COALESCE(NEW.raw_user_meta_data ->> 'first_name', ''),
      COALESCE(NEW.raw_user_meta_data ->> 'last_name', ''),
      NEW.raw_user_meta_data ->> 'middle_name',
      NEW.raw_user_meta_data ->> 'contact_number'
    );
  ELSE
    INSERT INTO public.students (user_id, username, first_name, last_name, middle_name, contact_number, grade_level, section)
    VALUES (
      NEW.id,
      COALESCE(NEW.raw_user_meta_data ->> 'username', NEW.email),
      COALESCE(NEW.raw_user_meta_data ->> 'first_name', ''),
      COALESCE(NEW.raw_user_meta_data ->> 'last_name', ''),
      NEW.raw_user_meta_data ->> 'middle_name',
      NEW.raw_user_meta_data ->> 'contact_number',
      NEW.raw_user_meta_data ->> 'grade_level',
      NEW.raw_user_meta_data ->> 'section'
    );
  END IF;

  RETURN NEW;
END;
$$;

-- ============================================================
-- 6. TRIGGERS
-- ============================================================

-- Auto-update updated_at on modification
CREATE TRIGGER update_students_updated_at
  BEFORE UPDATE ON public.students
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_admins_updated_at
  BEFORE UPDATE ON public.admins
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_document_requests_updated_at
  BEFORE UPDATE ON public.document_requests
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_payments_updated_at
  BEFORE UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_feedback_updated_at
  BEFORE UPDATE ON public.feedback
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_announcements_updated_at
  BEFORE UPDATE ON public.announcements
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Auto-create profile on new user signup (Supabase Auth trigger)
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- 7. RLS POLICIES
-- ============================================================

-- USER_ROLES policies
CREATE POLICY "Users can view their own roles"
  ON public.user_roles FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all roles"
  ON public.user_roles FOR SELECT
  USING (has_role(auth.uid(), 'admin'));

-- NOTE: No INSERT policy for user_roles. Only the handle_new_user
-- trigger (SECURITY DEFINER) can assign roles, preventing privilege escalation.

-- STUDENTS policies
CREATE POLICY "Students can view own profile"
  ON public.students FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all students"
  ON public.students FOR SELECT
  USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Users can insert own student profile"
  ON public.students FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own student profile"
  ON public.students FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can delete students"
  ON public.students FOR DELETE
  USING (has_role(auth.uid(), 'admin'));

-- ADMINS policies
CREATE POLICY "Admins can view all admins"
  ON public.admins FOR SELECT
  USING (has_role(auth.uid(), 'admin'));

-- NOTE: No INSERT policy for admins. Only the handle_new_user
-- trigger (SECURITY DEFINER) can create admin profiles, preventing
-- unauthorized self-registration as admin.

CREATE POLICY "Admins can update own profile"
  ON public.admins FOR UPDATE
  USING (auth.uid() = user_id);

-- DOCUMENT_REQUESTS policies
CREATE POLICY "Students can view own requests"
  ON public.document_requests FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all requests"
  ON public.document_requests FOR SELECT
  USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Students can insert own requests"
  ON public.document_requests FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can update all requests"
  ON public.document_requests FOR UPDATE
  USING (has_role(auth.uid(), 'admin'));

-- DOCUMENT_REQUEST_ITEMS policies
CREATE POLICY "Users can view items of their requests"
  ON public.document_request_items FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM document_requests
      WHERE document_requests.id = document_request_items.request_id
        AND (document_requests.user_id = auth.uid() OR has_role(auth.uid(), 'admin'))
    )
  );

CREATE POLICY "Students can insert items for own requests"
  ON public.document_request_items FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM document_requests
      WHERE document_requests.id = document_request_items.request_id
        AND document_requests.user_id = auth.uid()
    )
  );

-- PAYMENTS policies
CREATE POLICY "Students can view own payments"
  ON public.payments FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all payments"
  ON public.payments FOR SELECT
  USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Students can insert own payments"
  ON public.payments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can update payments"
  ON public.payments FOR UPDATE
  USING (has_role(auth.uid(), 'admin'));

-- FEEDBACK policies
CREATE POLICY "Students can view own feedback"
  ON public.feedback FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all feedback"
  ON public.feedback FOR SELECT
  USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Students can insert own feedback"
  ON public.feedback FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can update feedback status"
  ON public.feedback FOR UPDATE
  USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can delete feedback"
  ON public.feedback FOR DELETE
  USING (has_role(auth.uid(), 'admin'));

-- ANNOUNCEMENTS policies
CREATE POLICY "Authenticated users can view announcements"
  ON public.announcements FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can insert announcements"
  ON public.announcements FOR INSERT
  WITH CHECK (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can update announcements"
  ON public.announcements FOR UPDATE
  USING (has_role(auth.uid(), 'admin'));

CREATE POLICY "Admins can delete announcements"
  ON public.announcements FOR DELETE
  USING (has_role(auth.uid(), 'admin'));
